#!/usr/bin/with-contenv sh

echo "Starting dnsmasq..."
# Running dnsmasq as root prevents needing to run the entire container with --cap-add=NET_ADMIN
dnsmasq --user=root --keep-in-foreground --log-facility=/dev/stdout
