#!/usr/bin/with-contenv sh

# Set the containers name servers - so it can download the blacklist even if the host is using this container as DNS.
echo "nameserver $NS1" > /etc/resolv.conf
echo "nameserver $NS2" >> /etc/resolv.conf

echo
echo "-------------------------------------"
echo "BLACKLIST URL: $BLACKLIST_URL"

# Enable/Disable DNSCrypt - Default = OFF
if [ "$DNSCRYPT" = "1" ]; then
  echo "DNSCRYPT: Enabled"

  if [ ! -z "$DNS_CRYPT_SERVERS" ]; then
    for job in $(echo "$DNS_CRYPT_SERVERS" | tr "," " "); do
      export _DNS_CRYPT_SERVERS="$_DNS_CRYPT_SERVERS'${job}', "
    done

    sed -i "s/server_names =.*/server_names = [$_DNS_CRYPT_SERVERS]/" /etc/dnscrypt-proxy.toml
  fi

  sed -i "s/server=.* # NS1.*/server=127.0.0.1#40 # NS1/" /etc/dnsmasq.conf
  sed -i "s/server=.* # NS2.*/server=127.0.0.1#40 # NS2/" /etc/dnsmasq.conf

  # Allow the dnscrypt-proxy to start
  [ -d /etc/services.d/.dnscrypt-proxy ] && mv /etc/services.d/.dnscrypt-proxy /etc/services.d/dnscrypt-proxy
else
  echo "FORWARD NAME SERVERS: $NS1, $NS2"

  sed -i "s/server=.* # NS1.*/server=$NS1 # NS1/" /etc/dnsmasq.conf
  sed -i "s/server=.* # NS2.*/server=$NS2 # NS2/" /etc/dnsmasq.conf

  # Stop the dnscrypt-proxy starting
  [ -d /etc/services.d/dnscrypt-proxy ] && mv /etc/services.d/dnscrypt-proxy /etc/services.d/.dnscrypt-proxy
fi

echo "DEBUG LEVEL: $DEBUG"
echo "AUTO UPDATE: $AUTO_UPDATE"
echo "-------------------------------------"
echo

# Add domains to the whitelist
if [ ! -z "$WHITELIST" ]; then
  > /etc/dnsmasq.whitelist
  [ "$DNSCRYPT" = "1" ] && NS1="127.0.0.1#40" NS2="127.0.0.1#40"
  for job in $(echo "$WHITELIST" | tr "," " "); do
    echo "server=/$job/$NS1" >> /etc/dnsmasq.whitelist
    echo "server=/$job/$NS2" >> /etc/dnsmasq.whitelist
    echo "Added domain to whitelist: $job"
  done
fi

# Enable/Disable Debug Mode - Default = OFF
if [ "$DEBUG" = "1" ]; then
  sed -i "s/.*log-queries.*/log-queries/" /etc/dnsmasq.conf
elif [ "$DEBUG" = "2" ]; then
  sed -i "s/.*log-queries.*/log-queries=extra/" /etc/dnsmasq.conf
else
  sed -i "s/.*log-queries.*/#log-queries/" /etc/dnsmasq.conf
fi

# Enable/Disable Auto Update Mode - Default = ON
if [ "$AUTO_UPDATE" = "1" ]; then
  echo "0	*	*	*	*	/etc/cont-init.d/50-update-blacklist" > /var/spool/cron/crontabs/root
  # Allow the cron service to start
  [ -d /etc/services.d/.crond ] && mv /etc/services.d/.crond /etc/services.d/crond
else
  > /var/spool/cron/crontabs/root
  # Stop the cron service starting
  [ -d /etc/services.d/crond ] && mv /etc/services.d/crond /etc/services.d/.crond
fi
