#!/usr/bin/with-contenv sh

echo "Blacklist URL: $BLACKLIST_URL"
echo "Forward Name Servers: $NS1, $NS2"
echo "Debug Level: $DEBUG"
echo "Auto Update: $AUTO_UPDATE"

sed -i "s/server=.* # NS1.*/server=$NS1 # NS1/" /etc/dnsmasq.conf
sed -i "s/server=.* # NS2.*/server=$NS2 # NS2/" /etc/dnsmasq.conf

# Set the containers name servers - so it can download the blacklist even if the host is using this container as DNS.
echo "nameserver $NS1" > /etc/resolv.conf
echo "nameserver $NS2" >> /etc/resolv.conf

# Enable/Disable Debug Mode
if [[ "$DEBUG" -eq "1" ]]; then
  sed -i "s/.*log-queries.*/log-queries/" /etc/dnsmasq.conf
elif [[ "$DEBUG" -eq "2" ]]; then
  sed -i "s/.*log-queries.*/log-queries=extra/" /etc/dnsmasq.conf
else
  sed -i "s/.*log-queries.*/#log-queries/" /etc/dnsmasq.conf
fi

# Enable/Disable Auto Update Mode
if [[ "$AUTO_UPDATE" -eq "1" ]]; then
  echo "0	*	*	*	*	/etc/cont-init.d/50-update-blacklist" > /var/spool/cron/crontabs/root
else
  > /var/spool/cron/crontabs/root
fi
