#!/usr/bin/with-contenv sh

# Download the checksum on the remote release
CHECKSUM=$(curl -sk "$BLACKLIST_URL.checksum")

# Compare the remote checksum to the existing local file
echo "${CHECKSUM}  /etc/dnsmasq.blacklist" | sha256sum -c -

if [[ $? != 0 ]] ; then
  echo "Blacklist is missing or out of date, downloading update..."
  # Get the blacklist of domains and fix the zone file path.
  curl --progress -k -o /etc/dnsmasq.blacklist "$BLACKLIST_URL"

  # Kill any instances of dnsmasq
  # s6-supervisor will bring this back up if this script is being executed by crontab
  pkill dnsmasq
fi

echo "*** BLOCKING $(cat /etc/dnsmasq.blacklist | wc -l) BLACKLISTED DOMAINS ***"
